name: build

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run Advent of Code 2022
      run: python -m aoc22

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: |
        python -m pip install poetry
        poetry install
    - name: Run tests
      run: poetry run pytest
